### ISSUE TITLE
The released file is really right?

### ISSUE THREAD

**Issue by yangdongchao** [BytedanceSpeech/seed-tts-eval#2]
I check your released common-voice evalution set. I find the ground truth transrciption connot align with the audio. e.g.
common_voice_en_167249-common_voice_en_167247|Play the song from the genre Sunshine Reggae that appeals to me.|prompt-wavs/common_voice_en_167249.wav|Take these capsules over to Mrs. David's house.
 
Abviously, the common_voice_en_167249-common_voice_en_167247.wav   is not "Take these capsules over to Mrs. David's house."

**Comment by faceless-rex** [comment]
> I check your released common-voice evalution set. I find the ground truth transrciption connot align with the audio. e.g. common_voice_en_167249-common_voice_en_167247|Play the song from the genre Sunshine Reggae that appeals to me.|prompt-wavs/common_voice_en_167249.wav|Take these capsules over to Mrs. David's house.
> 
> Abviously, the common_voice_en_167249-common_voice_en_167247.wav is not "Take these capsules over to Mrs. David's house."
@yangdongchao  Hi

**Comment by yangdongchao** [comment]
> > I check your released common-voice evalution set. I find the ground truth transrciption connot align with the audio. e.g. common_voice_en_167249-common_voice_en_167247|Play the song from the genre Sunshine Reggae that appeals to me.|prompt-wavs/common_voice_en_167249.wav|Take these capsules over to Mrs. David's house.
> > Abviously, the common_voice_en_167249-common_voice_en_167247.wav is not "Take these capsules over to Mrs. David's house."
> 
> @yangdongchao Hi, the text of "wavs/common_voice_en_167249-common_voice_en_167247.wav" is exactly "Take these capsules over to Mrs. David's house.". You might have checked a wrong file.

You can hear the common_voice_en_167249-common_voice_en_167247.wav in your released seedtts_testset/en/wavs
