### ISSUE TITLE
How is it deployed ?

### ISSUE THREAD

**Issue by jinde98** [BytedanceSpeech/seed-tts-eval#3]
Is it possible to come up with a plan on how to deploy and apply it?

**Comment by faceless-rex** [comment]
@jinde98 Thanks for your attention on our projects. In consideration of AI safety, the source code and model weights of seed-TTS will not be released. You can explore the speech generation feature available within ByteDance's products.

**Comment by lphkxd** [comment]
> @jinde98感谢您对我们项目的关注。出于人工智能安全的考虑，seed-TTS 的源代码和模型权重将不会发布。您可以探索字节跳动产品中提供的语音生成功能。

不对外开放，就出来呲个牛逼？

**Comment by wavelet2008** [comment]
阿里牛逼
