### ISSUE TITLE
既然没有开源，那这个github上的项目是个什么，试用产品？

### ISSUE THREAD

**Issue by 863168558** [BytedanceSpeech/seed-tts-eval#4]
既然没有开源，那这个github上的项目是个什么，试用产品？

也没看明白如何试用

**Comment by ccjjfdyqlhy** [comment]
在README里写的很清楚，这只是论文中用来对模型生成内容进行评估的脚本框架，不包含模型核心代码和权重。

**Comment by faceless-rex** [comment]
@863168558  Thanks for your attention on our projects. In consideration of AI safety, the source code and model weights of seed-TTS will not be released. You can explore the speech generation feature available within ByteDance's products.
