### ISSUE TITLE
不对外开放，就出来呲个牛逼？

### ISSUE THREAD

**Issue by lphkxd** [BytedanceSpeech/seed-tts-eval#5]

**Comment by lixingyangok** [comment]
这个 issue 真是新时代赛博礼仪的典范

**Comment by faceless-rex** [comment]
@lphkxd Thanks for your attention on our projects. In consideration of AI safety, the source code and model weights of seed-TTS will not be released. You can explore the speech generation feature available within ByteDance's products.
