### ISSUE TITLE
Please don't advitise on opensource platform . 

### ISSUE THREAD

**Issue by VpJokor** [BytedanceSpeech/seed-tts-eval#6]
Please don't advitise on opensource platform . By wasting develop's attention for your bessiness action is very shame. Please stop your ugly Action now.

**Comment by faceless-rex** [comment]
> Please don't advitise on opensource platform . By wasting develop's attention for your bessiness action is very shame. Please stop your ugly Action now.

@VpJokor  Thanks for your attention on our projects. This repository is solely for academic purposes, providing the test set and evaluation tools. In consideration of AI safety, the source code and model weights of seed-TTS will not be released.
