### ISSUE TITLE
什么也不发布也算开源项目?

### ISSUE THREAD

**Issue by aceliuchanghong** [BytedanceSpeech/seed-tts-eval#7]
草

**Comment by jclioo** [comment]
草

**Comment by xgd** [comment]
坑蒙拐骗

**Comment by vjeson** [comment]
应该屏蔽这种项目，自家平台慢慢做广告去

**Comment by lphkxd** [comment]
真tm垃圾，就出来茨个牛逼

**Comment by faceless-rex** [comment]
Thanks for your attention on our projects. This repository is solely for academic purposes, providing the test set and evaluation tools. In consideration of AI safety, the source code and model weights of seed-TTS will not be released.

**Comment by faceless-rex** [comment]
Thanks for your attention on our projects. This repository is solely for academic purposes, providing the test set and evaluation tools. In consideration of AI safety, the source code and model weights of seed-TTS will not be released.

**Comment by jcao-ai** [comment]
> Thanks for your attention on our projects. This repository is solely for academic purposes, providing the test set and evaluation tools. In consideration of AI safety, the source code and model weights of seed-TTS will not be released.

一个免责声明（数字千年法案）就可以的事，说白了就是站在巨人肩膀上了还不想做回馈贡献😄

**Comment by Gujiuzean** [comment]
草
